#!/bin/bash
#SBATCH --partition=gagalli-ivyb
#SBATCH --mail-type=FAIL,END
#SBATCH --time=2:00:00
#SBATCH --ntasks-per-node=20
#SBATCH --nodes=4

#------------------------------------------------
# Thiophene coupling as a function of angular difference at 5 Ang distance

# It is needed to have good starting wavefunctions corresponding to the 
#  starting geometry of the CDFT run

# This is a short script for running the ground-state calculations in Qbox
#   for a set of bond distances for the thiophene dimer electron coupling example

# requires a modified version of Qbox that can handle external potentials
#------------------------------------------------

NCORES=$(($SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES))

#TODO: substitute the appropriate path of the Qbox executable
export qb="/path/to/executable/qb"

inputs=$( ls *.in )

# run gs calculation in Qbox
for inp in ${inputs[@]}; do
  IFS='.' read -ra name <<< $inp
  fol=$name
 
  mkdir $fol
  cd $fol
  
  cp ../{${fol}.in,${fol}.cif,*1.0.xml} .
  
  echo "===  Running Qbox ===="
  mpirun -np $NCORES $qb < ${name}.in > ${name}.out 
  
  cd ../
done
